/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include<stdio.h>


#include<led.h>
#include<switch.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


void delay(volatile uint32_t p)
{
    while(p--);
}


int main(void)
{
    switch_init(SWITCH_PIN);

    led_init(LED_GREEN);
    led_init(LED_ORANGE);
    led_init(LED_RED);
    led_init(LED_BLUE);


    int mode = 0;

    while(1)
    {
        if(switch_status(SWITCH_PIN))
        {
            delay(200000);

            if(switch_status(SWITCH_PIN))
            {

                mode = (mode + 1) % 4;


                while(switch_status(SWITCH_PIN));
            }
        }



        if(mode == 0)
        {

            led_off(LED_GREEN);
            led_off(LED_ORANGE);
            led_off(LED_RED);
            led_off(LED_BLUE);
        }
        else if(mode == 1)
        {

            led_on(LED_GREEN);
            led_on(LED_ORANGE);
            led_on(LED_RED);
            led_on(LED_BLUE);
        }
        else if(mode == 2)
        {

            led_on(LED_GREEN);
            delay(300000);
            led_off(LED_GREEN);

            led_on(LED_ORANGE);
            delay(300000);
            led_off(LED_ORANGE);

            led_on(LED_RED);
            delay(300000);
            led_off(LED_RED);

            led_on(LED_BLUE);
            delay(300000);
            led_off(LED_BLUE);
        }
        else if(mode == 3)
        {

            led_on(LED_GREEN);
            led_on(LED_RED);
            led_off(LED_ORANGE);
            led_off(LED_BLUE);
            delay(300000);

            led_off(LED_GREEN);
            led_off(LED_RED);
            led_on(LED_ORANGE);
            led_on(LED_BLUE);
            delay(300000);
        }
    }
}
